# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EW0x-ZSFvCPoFdaTG-FMlwLf1vGMnMVm
"""

class Person :
    def __init__(self, name, age, address):
        self.__name =name
        self.__age =age
        self.__address =address

    def set_name(self, name):
        self.__name = name
    def get_name(self):
        return self.__name


    def get_age(self):
        return self.__age
    def set_age(self, age):
        self.__age= age

    def get_address(self):
       return self.__address
    def set_address(self, address):
        self.__address= address
p = Person(name= "mahum", age = 100,address = "Lahore")
p.set_name("mahum")
p.set_age(100)

print(p.get_name())
print(p.get_age())
print(p.get_address())